package com.unl.map.sdk.data

import unl.core.UnlCore

/**
 * [GridCell] is an [KotlinData] Class to store data Related to Selected [GridCell].
 *
 * @property locationId is a Location Id of a Cell selected from Grid and this id is generated by [UnlCore] Lib.
 * @property size is Dimensions of a Cell Selected.
 * @constructor Create empty Grid cell
 */
data class GridCell(
    val locationId: String,
    val size: String
)